### ISSUE TITLE
Lat/Lon

### ISSUE THREAD

**Issue by lkilcher** [lkilcher/dolfyn-testing#4]
@jmcvey3-

It looks like you're dropping the non-unique latitude data. While this may seem to make sense at first, the problem is that we need to somehow preserve the connection to the _ADCP ping_ at which the lat/lon data was observed. Right now you have saved the `time_gps` data, but that is a *different* clock from `time` (which is the ADCP's clock). Therefore, you can't simple interpolate one onto the other (or whatever) because `time` can drift, and `time_gps` might not be perfectly synchronized.

I think what happens here is that the gps sends it's latest fix whenever it has one. When it doesn't update for a few pings, the pings record the same value of gps (or maybe that's how dolfyn reads it?). Either way, we need to know the ping that saw a new unique gps string (timestamp, lat, lon, etc.). Without that info, we can't actually sync the data to gps time.

So, I need you to either:
1. Make the gps data (time_gps, lat_gps, lon_gps, etc.) the same size as the `time`, `vel`, `...` data.
2. Add some kind of `gps_time_sync` varialbe that can be used to map pings to gps timestamps.

**Comment by jmcvey3** [comment]
Ohhhh, that's what going on. So vmdas is retrieving lat/lon based on the ADCP clock, but it still saves the GPS clock. Weird.

I was assuming lat/lon was still based on the GPS clock, which is shorter than the ADCP clock (drift?), and removing lat/lon values as such.

**Comment by jmcvey3** [comment]
Solved by [f47364b](https://github.com/jmcvey3/dolfyn/commit/f47364b2cb407e9c877fa904ecc21601a9ba5fdb)

**Comment by jmcvey3** [comment]
Ha, so after fixing this, there's now more data in xarray dolfyn than h5py dolfyn. May be similar to the Vector, where data length was 101 instead of 99

**Comment by lkilcher** [comment]
Does this mean that tests fail now? Or did you have to update a bunch of the test-data files to match? I guess I'm concerned if what seems like it should be a small change ends up having a bunch of unanticipated consequences. I'll take a look...

**Comment by lkilcher** [comment]
Which data files got bigger?

**Comment by lkilcher** [comment]
After thinking about this more, I think we should go back to how you had it -- having a separate `time_gps` that does not necessarily match the size of the other variables -- but we should add a `hwtime_gps` (with coordinate `time_gps`) that stores the timestamp from the instrument.

**Comment by lkilcher** [comment]
Just to be 100% clear, the following variables will be stored each time a gps_string appears in the RDI file:
- `time_gps` (dim: `time_gps`) - the timestamp in the GPS string
- `hwtime_gps` (dim: `time_gps`) - the timestamp from the instrument where the GPS string appears
- `longtiude_gps` (dim: `time_gps`) - longitude from the GPS string
- `latitude_gps` (dim: `time_gps`) - latitude from the GPS string

There should be no 'duplicate' values of lon/lat/time_gps.

**Comment by jmcvey3** [comment]
> Just to be 100% clear, the following variables will be stored each time a gps_string appears in the RDI file:
> 
> * `time_gps` (dim: `time_gps`) - the timestamp in the GPS string
> * `hwtime_gps` (dim: `time_gps`) - the timestamp from the instrument where the GPS string appears
> * `longtiude_gps` (dim: `time_gps`) - longitude from the GPS string
> * `latitude_gps` (dim: `time_gps`) - latitude from the GPS string
> 
> There should be no 'duplicate' values of lon/lat/time_gps.

Sounds logical to me. I know that Vmdas outputs a few different datafiles of varying QC, including GPS-correction, so I'll add an attribute logging if GPS-correction was applied. I don't believe WinRiver does this

**Comment by jmcvey3** [comment]
Note I used 'hdwtime_gps' instead: [7423584](https://github.com/jmcvey3/dolfyn/commit/7423584bbdc04694eff4a7eeffc7311b92085230)
