### ISSUE TITLE
ensemble counters in Signature reader

### ISSUE THREAD

**Issue by lkilcher** [lkilcher/dolfyn-testing#6]
The `ensemble_count_bt` and `ensemble_count_echo` variables are filled with `1`. I *think* these variable should match what is in `ensemble_count`, right? Somehow the data in the binary file doesn't appear to be propogating into the dataset?

**Comment by jmcvey3** [comment]
It was getting overwritten for every loop of the reader because of something I thought was an inconsequential change (go figure). Commit #[5427f4b](https://github.com/jmcvey3/dolfyn/commit/5427f4b93b833c59cdb6e82ed68774202e4dbe37)

Also did some cleanup in that commit

**Comment by lkilcher** [comment]
@jmcvey3 - The ensemble counters for Signature data in `dolfyn-xarray` start at 0, but the ones in `dolfyn-h5py` start at 1. I think the binary data (i.e., written by Nortek in the .ad2cp files) has 1-based counters? We should use whatever is there. Am I wrong? Are you creating a new counter somehow (that starts at 0)?

**Comment by jmcvey3** [comment]
@lkilcher Oh ha, good catch. I think it does, but the issue arose (I think) due to that [0 1] ensemble counter in the .index file from instruments running in "burst" mode. (I'm using a secondary `ensemble` counter that you have in the `read_signature` code, and it starts at 0.)

**Comment by jmcvey3** [comment]
Should be solved by [this commit](https://github.com/jmcvey3/dolfyn/commit/5655660f6f7d3d48ea4f0d6da34d92623015e80b)
