### ISSUE TITLE
Calculating stress and tke_vec

### ISSUE THREAD

**Issue by lkilcher** [lkilcher/dolfyn-testing#8]
OK, I'm pretty sure dolfyn-xarray is doing something wrong when computing tke_vec and stress.

**Comment by lkilcher** [comment]
See the figures, and script, added in 8aca185.

**Comment by jmcvey3** [comment]
Ah, maybe this is it.
This is the function used in dolfyn-xarray to calculate tke: `out = np.nanmean(self.demean(vel)**2, -1, dtype=np.float64).astype('float32')`

In dolfyn 12.0: `out = np.mean(self.detrend(vel)**2, -1, dtype=np.float64).astype('float32')`

Not sure why I changed it, but is using detrend more stable than demean?

**Comment by lkilcher** [comment]
Yep, that's most likely the reason for the discrepancy. Now the question is: which way is the *right* way to do it?! Honestly, if you'd asked me without looking at this, I'd tell you: "just use `demean`". But since I've been using `detrend`, I'm remembering that there are good reasons for that too. I think we need to make this an option in the function somewhere. I'm thinking it could/should be an option at the `VelBinner` class level (i.e., `binner = dlfn.VelBinner(n_bin,fs,demean_mode='demean')`, but it could also be at the method level (`tke = binner.calc_tke(veldat,demean_mode='demean')`). Any opinions/thoughts?

**Comment by jmcvey3** [comment]
> Yep, that's most likely the reason for the discrepancy. Now the question is: which way is the _right_ way to do it?! Honestly, if you'd asked me without looking at this, I'd tell you: "just use `demean`". But since I've been using `detrend`, I'm remembering that there are good reasons for that too. I think we need to make this an option in the function somewhere. I'm thinking it could/should be an option at the `VelBinner` class level (i.e., `binner = dlfn.VelBinner(n_bin,fs,demean_mode='demean')`, but it could also be at the method level (`tke = binner.calc_tke(veldat,demean_mode='demean')`). Any opinions/thoughts?

And the answer to that question is likely "it depends", eh? Option-wise, I'm inclined to add it at the method level since these are the only two functions that use it.

**Comment by lkilcher** [comment]
This is resolved mostly by [this](https://github.com/lkilcher/dolfyn/pull/67/commits/3be3f6983a14826fd35390e8f76407fcf164adf7), and finalized with 2f5e0d4 .
