### ISSUE TITLE
Sig1000 IMU earth2inst rotations

### ISSUE THREAD

**Issue by lkilcher** [lkilcher/dolfyn-testing#9]
Not sure why these rotations don't match, but they don't. File: `Sig1000_IMU_rotate_inst2earth`

**Comment by lkilcher** [comment]
See the figures/script in 1a63c40 for details.

**Comment by lkilcher** [comment]
@jmcvey3

If you've checked this against Nortek scripts/tools, I'm going to trust that you/they are getting the rotation result correct.

However, I still want to make sure we're implementing this in a way that is consistent with DOLfYN's approach more generally. Specifically, I've tried to take the approach that:
- DOLfYN modifies/creates the rotation matrix at *read*-time so that it is always the "earth->inst" rotation matrix, as [documented here](https://lkilcher.github.io/dolfyn/rotations.html#orientation-data).
- That (hopefully) being the case, I just want to make sure that's what we're doing here?

... Yes, we should probably discuss. I'm generally available today - Wednesday.

**Comment by jmcvey3** [comment]
@lkilcher 

I am trusting them as well.

I ended up correcting the coordinate names on the matrix, so that it does read "inst->earth". It would clean up the rotate code to transform the AHRS rotation matrix to "earth->inst" at "read-time", so I'll hopefully get to that next week.

I believe I have time next Thursday-Friday next week to discuss.

**Comment by jmcvey3** [comment]
> @lkilcher
> 
> I am trusting them as well.
> 
> I ended up correcting the coordinate names on the matrix, so that it does read "inst->earth". It would clean up the rotate code to transform the AHRS rotation matrix to "earth->inst" at "read-time", so I'll hopefully get to that next week.
> 
> I believe I have time next Thursday-Friday next week to discuss.

Should all be standardized again to "earth2inst" : [this commit](https://github.com/jmcvey3/dolfyn/commit/1db8fe67ab87df3ad1909e6c97acd877869e9e9e)

**Comment by lkilcher** [comment]
I'm going to trust that this is good to go for now. I'll have the chance to check it while data processing the Cook Inlet dataset. I think we're ready to merge [#67](https://github.com/lkilcher/dolfyn/pull/67)!! What do you think?
